server:
  port: 8762

spring:
  application:
    name:
      eureka-server

eureka:
  instance:
    hostname: account-server
  client:
    register-with-eureka: true  # 是否向注册中心注册自己
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/